server:
  port: 4040
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: withme
  profiles:
    default: production

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  ai:
    openai:
      api-key: ENC(e98opFQhXMb/cgglbri7+dNns98aLam2yL+QDgpqgXogquYxAlnDahfVNnUGrPt0hdsrkZ0WqdBsHnaX0NfDHvNdpoej+WW4l0FEn6zv5D3qrFgU26zWR0cxTlpamrCNPw7bigsk8jOGEjxeP0nr2pWSWgoPfKhRk0eLeGjdz2tqOzn8eNfGloBurvMiholNLhtFBUF8BunO8TTAaLhm+8hCSR0SwjRBB+TMj9RFwWk=)
      base-url: https://api.openai.com

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(lshpf6tM+tGvUolf3Qmw79kDmR1XC4v5/CWiA8Uons4=)
            client-secret: ENC(HpjwapT8/QRAcWHifNO2gsV3n29y03WBTo7xCaBUF+EmuWGvT2qU1iDbnDwZhZCKE5iOoJBmmXA=)
            redirect-uri: ${client.base-url}/login/callback

  webflux:
    base-path: http://localhost:4040

client:
  base-url: http://localhost:3000

jwt:
  key-string: ENC(s36WwIXzzl9GZ83rGz7AIJgXaQCUuPfe6zBjQdz2x2vsRUcmEiXuNk2yF4JIlr1QBYWGnLAMOSs=)
  expires-in:
    access: 14400
    refresh: 2592000 #30일