server:
  port: 4040

spring:
  application:
    name: withme
  profiles:
    default: production

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  ai:
    openai:
      api-key: ENC(e98opFQhXMb/cgglbri7+dNns98aLam2yL+QDgpqgXogquYxAlnDahfVNnUGrPt0hdsrkZ0WqdBsHnaX0NfDHvNdpoej+WW4l0FEn6zv5D3qrFgU26zWR0cxTlpamrCNPw7bigsk8jOGEjxeP0nr2pWSWgoPfKhRk0eLeGjdz2tqOzn8eNfGloBurvMiholNLhtFBUF8BunO8TTAaLhm+8hCSR0SwjRBB+TMj9RFwWk=)